---
- name: Provision system
  hosts: all
  environment:
    http_proxy: '{{ http_proxy }}'
  vars_files: vars.os.yaml
  tasks:
    - name: Create storage stack (ESP + thin LVM)
      ansible.builtin.import_tasks:
        file: esp_plus_thin_lvm.yml
    - name: Prepare chroot
      ansible.builtin.import_tasks:
        file: prepare_chroot.yml

- name: Provision OS
  hosts: chroots
  connection: community.general.chroot
  environment:
    http_proxy: '{{ http_proxy }}'
  tasks:
    - name: Configure Debian 12
      ansible.builtin.import_tasks:
        file: configure_debian_12.yml
