---
- name: Get build info
  when: 0>1
  ansible.builtin.debug:
    msg:
    - "{{ build_slug }}"
    - "{{ os_info[build_slug]['codename'] }}"
    - "{{ os_info[build_slug] }}"

- name: debootstrap
  block:
    - name: Install debootstrap
      ansible.builtin.package:
        name: debootstrap
        state: present
    - name: Bootstrap base system
      ansible.builtin.shell:
        cmd: debootstrap --verbose --include=python3 {{ os_info[build_slug]['codename'] }} {{ chroot_root }} {{ os_info[build_slug]['mirror_url'] }}

- name: Mount virtual filesystems
  loop: "{{ chroot_mounts }}"
  ansible.posix.mount:
    path: "{{ item.dst }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    state: "{{ item.state }}"
    opts: "{{ item.opts }}"

- name: configure guest
  block:
    - name: populate resolv.conf
      ansible.builtin.shell:
        cmd: echo "nameserver 8.8.8.8" > /mnt/etc/resolv.conf
    - name: populate hostname
      ansible.builtin.shell:
        cmd: echo "debian" > /mnt/etc/hostname
    - name: populate fstab
      ansible.builtin.shell:
        cmd: genfstab -U /mnt > /mnt/etc/fstab
    - name: Add chroot to ansible inventory
      ansible.builtin.add_host:
        groups: chroots
        name: /mnt